import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const ProfilePage: NextPage = () => {
  const router = useRouter();

  const profileName = router.query.slug as string;

  return (
    <>
      <Head>
        <title>{`${profileName}'s Profile`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="h-36"></div>
          <div className="h-36 bg-slate-700"></div>
        </div>
      </main>
    </>
  );
};

export default ProfilePage
