import {
  SignIn,
  SignInButton,
  SignOutButton,
  UserButton,
  useUser,
} from "@clerk/nextjs";
import { log } from "console";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { BiLoader } from "react-icons/bi";

import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from 'dayjs/plugin/relativeTime';
dayjs.extend(relativeTime)

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full space-x-4">
      <Image
        src={user.profileImageUrl}
        alt={user.fullName ?? ""}
        width={56}
        height={56}
        className="rounded-full"
      />
      <input
        type="text"
        placeholder="Type some emojis here!"
        className="grow rounded-xl bg-transparent p-3 focus:outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][0];

const PostView = ({ post, author }: PostWithUser) => {
  if (!post) return null;
  return (
    <div className="flex items-center space-x-4 border-b border-slate-400 p-4 last:border-none">
      {author && (
        <Image
          src={author.profilePicture}
          alt={author.username ?? ""}
          width={56}
          height={56}
          className="rounded-full"
        />
      )}
      <div className="flex flex-col">
        <div className="text-slate-300">
          <span>{`@${author.username}`}</span> ∙ <span className="text-sm">{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <div className="text-2xl">{post.content}</div>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading)
    return (
      <div className="flex h-screen w-full flex-col items-center justify-center">
        <h1>Loading...</h1>
        <BiLoader className="animate-spin text-7xl" />
      </div>
    );

  if (!data) return <div className="">Something went wrong!</div>;

  return (
    <>
      <Head>
        <title>Twitter T3 Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex w-full items-center justify-center ">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
            {/* <UserButton /> */}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
