import {
  SignIn,
  SignInButton,
  SignOutButton,
  UserButton,
  useUser,
} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { BiLoader } from "react-icons/bi";

import { api } from "~/utils/api";


const CreatePostWizard = () => {
  const { user } = useUser();
}


const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading)
    return (
      <div className="flex h-screen w-full flex-col items-center justify-center">
        <h1>Loading...</h1>
        <BiLoader className="animate-spin text-7xl" />
      </div>
    );

  if (!data) return <div className="">Something went wrong!</div>;

  return (
    <>
      <Head>
        <title>Twitter T3 Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex w-full items-center justify-center ">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div className="">
                <SignOutButton />
              </div>
            )}
            {/* <UserButton /> */}
          </div>
          <div className="flex flex-col">
            {data?.map((post) => (
              <div
                key={post.id}
                className="border-b border-slate-400 p-8 last:border-none"
              >
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
