import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const SinglePostPage: NextPage = () => {
  const router = useRouter();

  // const profileName = router.query.slug as string;

  return (
    <>
      <Head>
        {/* <title>{`${profileName}'s Profile`}</title> */}
        <title>Single Post Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="">Single Post View</div>
      </main>
    </>
  );
};

export default SinglePostPage;
